baseURL = "https://maker.today/"
languageCode = "en-us"
title = "Maker Today"
theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "t04glovern"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-71336829-2"
# Enable Robots
enableRobotsTXT = true

# Syntax highlighting
PygmentsCodeFences = true
PygmentsStyle = "friendly"
# options = ['monokai', 'manni', 'rrt', 'perldoc', 'borland', 'colorful',
#   'default', 'murphy', 'vs', 'trac', 'tango', 'fruity', 'autumn' 'bw',
#   'emacs', 'vim', 'pastie', 'friendly', 'native']

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/t04glovern"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/glovers.id.au"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/nathangloverAUS"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:nathan@glovers.id.au"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Makers of Things"
    defaultKeywords = ["nathan", "rico", "stephen", "luke"]
    defaultDescription = "Maker Today website for WA Makers"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCL2TFW23o9qPBt_rLrSVz9sByNziMQRt0"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "nathan@glovers.id.au"

    about_us = "<p>We strive to build great things for interesting problems, and have fun atleast 80% of the time.</p>"
    copyright = "Copyright (c) 2017, Maker Today; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Maker Today.</strong>
        <br>125 St Georges Terrace, 6000
        <br>Perth, WA
        <br>
        <strong>Australia</strong>
      </p>
      """
    latitude = "-31.953512"
    longitude = "115.857048"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on nathan@glovers.id.au.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "Makers"
    subtitle = "Meet our team!"
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
        img = "nathan-glover.png"
        name = "Nathan Glover"
        position = "Computer Science"
        scope = [
            "B.Tech, Curtin, 2017"
        ]
        # For bio markdown and even multiline strings are available.
        bio = """I have a curious mind and enjoy exploring any and all fields of technology."""
        social = [
            ["fa-envelope", "mailto:nathan@glovers.id.au"],
            ["fa-linkedin", "https://linkedin.com/in/glovernathan"],
            ["fa-github", "https://github.com/t04glovern"],
            ["fa-home", "http://nathanglover.com"]
        ]
        center = true

    [[params.team.members]]
        img = "stephen-mott.png"
        name = "Stephen Mott"
        position = "Mechanical Engineer"
        scope = [
            "B.Science, UWA, 2018"
        ]
        bio = """Student at The University of Western Australia."""
        social = [
            ["fa-envelope", "mailto:stephen@mott.id.au"]
        ]
        center = true

    [[params.team.members]]
        img = "rico-beti.png"
        name = "Rico Beti"
        position = "Software Engineer"
        scope = [
            "B.Science, ECU, 2018"
        ]
        bio = """I’m a passionate software engineer of Swiss origin now living in Perth, WA."""
        social = [
            ["fa-envelope", "mailto:rico@beti.ch"],
            ["fa-linkedin", "https://www.linkedin.com/in/ricobeti"],
            ["fa-github", "https://github.com/SilentByte"],
            ["fa-home", "https://ricobeti.ch"]
        ]

    [[params.team.members]]
        img = "luke-stokes.png"
        name = "Luke Stokes"
        position = "Mechatronics Engineer"
        scope = [
            "B.Sc, Curtin, 2018"
        ]
        bio = """Student of Curtin University."""
        social = [
            ["fa-linkedin", "https://www.linkedin.com/in/luke-stokes-408321144"]
        ]

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "Check out some of our recent work!"
    link_url = "/blog/"
    link_text = "Recent Projects"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Maker Blog"
    subtitle = "What to check out some of the great stuff our team has been working on? Check out some of our latest posts!"
